# Generated by Django 3.2 on 2021-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.URLField(default=12),
            preserve_default=False,
        ),
    ]
