# Generated by Django 3.2 on 2021-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon_test_app', '0002_test_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='url',
            field=models.SlugField(),
        ),
    ]
